# Generated by Django 4.2.9 on 2024-01-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='education',
            field=models.CharField(choices=[('小学', '小学'), ('初中', '初中'), ('高中', '高中'), ('大学', '大学'), ('硕士', '硕士'), ('博士', '博士')], max_length=50, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='fan',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='review',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.album', verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='review',
            name='fan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fan', verbose_name='歌迷'),
        ),
    ]
