# Generated by Django 4.2.9 on 2024-01-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_bandmember_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
    ]
